name: TAG

on:
  push:
    tags:
      - '*'

jobs:
  nightly:
    name: Nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: 'true'
          fetch-depth: 0
      - uses: microsoft/setup-msbuild@v1.1

      # GitVersion action doesn't support /ensureassemblyinfo, see https://github.com/GitTools/actions/issues/220
      # So we need to create a new file to let GitVersion populate it
      - name: Create assembly info file for GitVersion
        shell: powershell
        run: |
          set-Content -Path 'Blish HUD/Properties/AssemblyVersionInfo.cs' -Value 'using System.Reflection;'
      - uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.13
        id: gitversion
        with:
          updateAssemblyInfo: true
          updateAssemblyInfoFilename: Blish HUD/Properties/AssemblyVersionInfo.cs

      - name: Run msbuild restore
        run: msbuild -t:restore
      - name: Run msbuild
        run: msbuild -p:Configuration=Release -p:VERSIONED_BUILD=${{ steps.gitversion.outputs.semVer }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Blish HUD ${{ steps.gitversion.outputs.semVer }}
          path: Blish HUD/bin/x64/Release/net472

      - name: Run dotnet pack
        run: dotnet pack "Blish HUD" -c Release -p:VERSIONED_BUILD=${{ steps.gitversion.outputs.semVer }}
      - name: Upload NuGet package artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Blish HUD ${{ steps.gitversion.outputs.semVer }} NuGet packages
          path: Blish HUD/bin/Release/BlishHUD.${{ steps.gitversion.outputs.semVer }}.*nupkg
